export default {
    data: {
        title: 'World',
        wechatNo: '12312321312312',
        arrowSrc: '/common/global/arrow-right.png',
        qrcodeSrc: '/common/global/qr_code.png',
        items: [{
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'head',
                }, {
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'divider',
                }, {
                    'name': '支付',
                    'index': 0,
                    'src': '/common/find/朋友圈.png',
                    'type': 'content',
                }, {
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'divider',
                }, {
                    'name': '收藏',
                    'index': 1,
                    'src': '/common/find/视频.png',
                    'type': 'content',
                }, {
                    'name': '相册',
                    'index': 2,
                    'src': '/common/find/扫一扫.png',
                    'type': 'content',
                }, {
                    'name': '卡包',
                    'index': 3,
                    'src': '/common/find/摇一摇.png',
                    'type': 'content',
                }, {
                    'name': '表情',
                    'index': 4,
                    'src': '/common/find/看一看.png',
                    'type': 'content',
                }, {
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'divider',
                }, {
                    'name': '设置',
                    'index': 5,
                    'src': '/common/find/搜一搜.png',
                    'type': 'content',
                }, {
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'divider',
                },],
    },
}
