export default {
    data: {
        title: 'World',
        items: [{
                    'name': '朋友圈',
                    'index': 0,
                    'src': '/common/find/朋友圈.png',
                    'type': 'content',
                }, {
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'divider',
                }, {
                    'name': '视频号',
                    'index': 1,
                    'src': '/common/find/视频.png',
                    'type': 'content',
                }, {
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'divider',
                }, {
                    'name': '扫一扫',
                    'index': 2,
                    'src': '/common/find/扫一扫.png',
                    'type': 'content',
                }, {
                    'name': '摇一摇',
                    'index': 3,
                    'src': '/common/find/摇一摇.png',
                    'type': 'content',
                }, {
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'divider',
                }, {
                    'name': '看一看',
                    'index': 4,
                    'src': '/common/find/看一看.png',
                    'type': 'content',
                }, {
                    'name': '搜一搜',
                    'index': 5,
                    'src': '/common/find/搜一搜.png',
                    'type': 'content',
                }, {
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'divider',
                }, {
                    'name': '附近的人',
                    'index': 6,
                    'src': '/common/find/附近的人.png',
                    'type': 'content',
                }, {
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'divider',
                }, {
                    'name': '购物',
                    'index': 7,
                    'src': '/common/find/购物.png',
                    'type': 'content',
                }, {
                    'name': '游戏',
                    'index': 8,
                    'src': '/common/find/游戏机.png',
                    'type': 'content',
                }, {
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'divider',
                }, {
                    'name': '小程序',
                    'index': 9,
                    'src': '/common/find/小程序.png',
                    'type': 'content',
                }, {
                    'name': '',
                    'index': -1,
                    'src': '',
                    'type': 'divider',
                },],
    },
}
